### ISSUE TITLE
"ReferenceError: Symbol is not defined" when running server with samples

### ISSUE THREAD

**Issue by evelinag** [fsprojects/Fable#175]
I just installed Fable and I wanted to look at the included samples. First I compiled the sample and then I also compiled the included server in `Fable/samples/node/server` by running the `fable` command in the directory. Then I wanted to get a preview of the samples by calling
``` node ../../node/server/out```
and I'm getting the following error:
```
/Users/evelina/Projects/Fable/samples/node/server/node_modules/fable-core/fable-core.js:23
    interfaces: Symbol("interfaces")
                ^
ReferenceError: Symbol is not defined
    at /Users/evelina/Projects/Fable/samples/node/server/node_modules/fable-core/fable-core.js:23:17
    at Object.defineProperty.value (/Users/evelina/Projects/Fable/samples/node/server/node_modules/fable-core/fable-core.js:7:5)
    at Object.<anonymous> (/Users/evelina/Projects/Fable/samples/node/server/node_modules/fable-core/fable-core.js:15:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/evelina/Projects/Fable/samples/node/server/out/index.js:13:18)
```
Thanks for any help.

**Comment by alfonsogarciacaro** [comment]
`Symbol` is a new object introduced in ES6, so it's possible you've a version of Node installed that doesn't support it yet. Can you please try updating Node? Not sure which is the minimum version but your safest bet is to install at least the latest stable: v4.4.

**Comment by evelinag** [comment]
Thanks for the help, this was the problem. Everything's working correctly now.
