### ISSUE TITLE
Typescript2Fable fails

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#20]
```
node tools/typescript2fable.js D:\Programowanie\Projekty\Fable-vscode-test\asd\typings\vscode-typings.d.ts > D:\Programowanie\Projekty\Fable-vscode-test\vscode.fs
module.js:340
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Programowanie\Projekty\Fable\tools\typescript2fable.js:2:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```
Looks like typescript is not defined as dependency in `packages.json`. Works well when I've added it to dependencies and run `npm install` again

**Comment by Krzysztof-Cieslak** [comment]
Fix in #21
