### ISSUE TITLE
updated - low priority - win7 need $ to call Node.require.Invoke

### ISSUE THREAD

**Issue by markek** [fsprojects/Fable#229]
Updated to reproduce in a fresh environment, using most recent fable that has compiler stack dump.

### Repro steps

~~~~
{
    "projFile": "index.fsx",
    "outDir": "out",
    "scripts": {
        "prebuild": "npm install"
    }
}

{
  "private": true,
  "dependencies": {
    "fable-core": "^0.2.3"
  },
  "engines": {
    "fable": "^0.4.3"
  }
}

#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
open Fable.Import.Node
let m = require.Invoke "any-name"
~~~~

### Expected behavior

No compiler issues

### Actual behavior
~~~~
Fable F# to JS compiler version 0.4.3
npm install

PROJECT FILE: D:\Users\mark\Desktop\express\index.fsx
OUTPUT DIR: D:\Users\mark\Desktop\express\out
WORKING DIR: D:\Users\mark\Desktop\express

FABLE COMMAND: cmd /S /C
 "D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\bin\Fable.Client.Node.exe
 --copyExt true --verbose true --projFile index.fsx
 --outDir D:\Users\mark\Desktop\express\out
 --ecma es5 --module umd"

Start compilation...
ERROR: unknown: Property right of AssignmentExpression expected node
to be of a type ["Expression"] but instead got null
TypeError: unknown: Property right of AssignmentExpression expected node
to be of a type ["Expression"] but instead got null
    at Object.validate (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-types\lib\definitions\index.js:109:13)
    at Object.validate (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-types\lib\index.js:541:9)
    at NodePath._replaceWith (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-traverse\lib\path\replacement.js:208:7)
    at NodePath._remove (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-traverse\lib\path\removal.js:58:10)
    at NodePath.remove (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-traverse\lib\path\removal.js:30:8)
    at PluginPass.CallExpression (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-plugin-transform-es2015-modules-amd\lib\index.js:42:12)
    at NodePath._call (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:12)
    at TraversalContext.visitQueue (D:\Users\mark\AppData\Roaming\npm\node_modules\fable-compiler\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:167:16)
~~~~

### Known workarounds

Use $ to make the call:

~~~~
#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
open Fable.Import.Node
let m = require.Invoke "any-name"
~~~~

### Related information 
~~~~
fresh aws workspace
64-bit dual core - windows server 2008 r2 data center sp1 - with a win 7 experience
Note the user's desktop is on a D: drive
vs community with updates, custom install, check f# language
msbuild tools 2013
node v4.4.7 lts 64-bit
fable-compiler 0.4.3
fable-core 0.2.3
~~~~

**Comment by alfonsogarciacaro** [comment]
Interesting, for me your example above it's working (without the `$` sign) on OSX. I'll try on Windows later to see if I can reproduce the problem.

**Comment by alfonsogarciacaro** [comment]
In the new version, the `$` operator shouldn't be needed in most cases anymore ([see docs](http://fsprojects.github.io/Fable/docs/interacting.html#Dynamic-programming)) and there also now [import expressions](http://fsprojects.github.io/Fable/docs/interacting.html#Import-attribute) so I'm closing the issue. Please feel free to reopen it if you still have the same problem with the new version.
