### ISSUE TITLE
build GenerateDocs fails on Windows

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#266]
One more build failure - I tried running `build GenerateDocs` and it failed because it could not find `fable-core.min.js`, which is probably due to #264. After changing the `docs.fsx` to use `fable-core.js` instead of `fable-core.min.js`, I got another error:

    Deleting contents of C:\Tomas\Public\fsprojects\Fable\temp
    node build/fable samples/node/nunit -o ../../../temp --symbols TUTORIAL
    npm install
    (...)
    Start compilation...
    Compiled index.fsx at 10:18:08 PM
    npm test

    > @ test C:\Tomas\Public\fsprojects\Fable\samples\node\nunit
    > mocha out

    ERROR: C:\Tomas\Public\fsprojects\Fable\samples\node\nunit\node_modules\mocha\lib\utils.js:634
        throw new Error("cannot resolve path (or pattern) '" + path + "'");

**Comment by alfonsogarciacaro** [comment]
I have changed the npm "test" script from `mocha out` to `mocha ./out`. I'll check later if this has fixed the problem on Windows.

**Comment by fdcastel** [comment]
Windows 8.1:

```
mkdir C:\AVeryLargeFolderNameLifeUniverseAndEverything
pushd C:\AVeryLargeFolderNameLifeUniverseAndEverything
git clone https://github.com/fsprojects/Fable.git
cd Fable
build
build FableCore
```

all fine in Windows 8.1. However,

`build GenerateDocs`

is failing with:

```
Generating sample page: mario
Compiling sample: mario
Deleting contents of C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\temp
node build/fable samples/browser/mario -o ../../../temp --symbols TUTORIAL
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\build\fable'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
 Running build failed.
Error:
System.Exception: 'C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable> node build/fable samples/browser/mario -o ../
../../temp --symbols TUTORIAL' task failed
   at FSI_0005.Helpers.Util.run(String workingDir, String fileName, String args) in C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\docs\helpers.fs:line 69
   at FSI_0005.Helpers.Node.run(String workingDir, String script, IEnumerable`1 args) in C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\docs\helpers.fs:line 74
   at FSI_0005.Docs.compileSample(Boolean copyOutput, String name, String path) in C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\docs\docs.fsx:line 200
   at FSI_0005.Docs.generateSamplePages(String siteRoot, Boolean recompile, Unit unitVar2) in C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\docs\docs.fsx:line 299
   at FSI_0005.Docs.clo@351-2.Invoke(Unit _arg2) in C:\AVeryLargeFolderNameLifeUniverseAndEverything\Fable\docs\docs.fsx:line 354
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492

```

**Comment by alfonsogarciacaro** [comment]
I tried on Windows. Actually the problem was that for the Docs, the sample code is output to another dir, so the command `mocha ./out` was pointing to an empty dir. This could be solved by using compile targets or maybe introducing macros (`mocha $(outDir)`), but for now I just removed the postbuild script.

@fdcastel, I don't have Windows 8.1 and this is something very specific about development, so I wouldn't worry too much about generating the docs with long folder names on this specific OS. But please feel free to send a PR if you find a way to fix the issue. 

Cheers!
