### ISSUE TITLE
Cannot find module 'babel-template'

### ISSUE THREAD

**Issue by ayuscode** [fsprojects/Fable#45]
After successfully build fable in windows (build.cmd), trying to test node sample (node tools/fable2babel.js --projFile sample/node/server/app.fsx) I get the error "Cannot find module 'babel-template'".

Repro:
- build.cmd
- cd sample/node/server
- npm install
- cd ../../..
- node tools/fable2babel.js --projFile sample/node/server/app.fsx

Error stack trace:
```javascript
module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-template'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (xxx_path_xxx\Fable-master\tools\fable2babel.js:7:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```
After exec "npm install babel-template" everything works ok.

Is "babel-template" missing from package.json?

**Comment by alfonsogarciacaro** [comment]
It was indeed! Thanks for letting me now :)
