### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#50]
The following code:

```
module Program

open System
open Fable.Import
open Fable.Core

[<EntryPoint>]
let main argv =
    let a = [ "prop" ==> "value" ]
    let b = createObj a
    0
```

Results in the following error

```
C:\Dev\Fable\lib\fable-core.js:977
      for (var i = 0, cur = null, iter = xs[Symbol.iterator](); ; i++) {
                                           ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.Seq.fold (C:\Dev\Fable\lib\fable-core.js:977:44)
    at Object.Util.createObj (C:\Dev\Fable\lib\fable-core.js:59:16)
    at C:\Dev\Fable\sample\node\react\Program.js:16:68
    at C:\Dev\Fable\sample\node\react\Program.js:17:5
    at Object.<anonymous> (C:\Dev\Fable\sample\node\react\Program.js:20:2)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

but the following code does work

```
module Program

open System
open Fable.Import
open Fable.Core

[<EntryPoint>]
let main argv =
    let b = createObj [ "prop" ==> "value" ]
    0
```

**Comment by alfonsogarciacaro** [comment]
Yeah, I noticed that today too :)I forgot to add `fields` in this [line](https://github.com/fsprojects/Fable/blob/master/lib/fable-core.js#L62) (and of course JS doesn't complain at all). It should be fixed now.
